package fr.atraore.edl.utils

val POSITION_FRAGMENT_BIENS = 0
val POSITION_FRAGMENT_PROPRIETAIRE = 1
val POSITION_FRAGMENT_LOCATAIRE = 2
val POSITION_FRAGMENT_MANDATAIRE = 3
val POSITION_FRAGMENT_AGENCES = 4

val ARGS_TAB_POSITION = "tabPosition"
val ARGS_CONSTAT_ID = "constatId"
val ARGS_CONSTAT = "constat"
val ARGS_ALREADY_ADDED = "alreadyAdded"
