package fr.atraore.edl.utils

val POSITION_FRAGMENT_BIENS = 0
val POSITION_FRAGMENT_PROPRIETAIRE = 1
val POSITION_FRAGMENT_LOCATAIRE = 2
val POSITION_FRAGMENT_MANDATAIRE = 3
val POSITION_FRAGMENT_AGENCES = 4

val ARGS_TAB_POSITION = "tabPosition"
val ARGS_CONSTAT_ID = "constatId"
val ARGS_CONSTAT = "constat"
val ARGS_ALREADY_ADDED = "alreadyAdded"

val PROPERTY_LABEL = "Biens"
val OWNER_LABEL = "Propriétaires"
val CONTRACTOR_LABEL = "Mandataires"
val TENANT_LABEL = "Locataires"
val AGENCY_LABEL = "Agences"
val USER_LABEL = "Utilisateurs"

val ROOMS_LABELS = arrayOf(
    "ACCES / ENTREE",
    "DEGAGEMENT",
    "CUISINE",
    "SEJOUR",
    "CHAMBRE",
    "SALLE DE BAINS",
    "WC",
    "GARAGE",
    "LOCAL TECHNIQUE",
    "CHAUFFERIE",
    "CELLIER",
    "BUANDERIE",
    "GRENIER",
    "CAVE",
    "EXTERIEURS",
    "POOL HOUSE",
    "DRESSING",
    "MEZZANINE",
    "CABANON",
    "MONTEE ESCALIER",
    "LOCAL COMMERCIAL - FACADES ET EXTERIEURS",
    "LOCAL COMMERCIAL - ACCUEIL",
    "LOCAL COMMERCIAL - PIECE",
    "LOCAL COMMERCIAL - CUISINE",
    "LOCAL COMMERCIAL - SANITAIRES"
)
