package fr.atraore.edl.utils

const val CONSTAT_TABLE = "Constat"
const val AGENCY_TABLE = "Agency"
const val OWNER_TABLE = "Owner"
const val USERS_TABLE = "User"
const val PROPERTY_TABLE = "Property"
const val DETAIL_TABLE = "Detail"
const val FAMILLE_TABLE = "Famille"
const val CONTRACTOR_TABLE = "Contractor"
const val DESCRIPTIF_TABLE = "Descriptif"
const val ALTERATION_TABLE = "Alteration"
const val CONFIG_PDF_TABLE = "ConfigPdf"
const val TENANT_TABLE = "Tenant"
const val ROOM_REFERENCE_TABLE = "RoomReference"
const val ELEMENT_REFERENCE_TABLE = "ElementReference"
const val LOT_REFERENCE_TABLE = "LotReference"
const val COMPTEUR_TABLE = "Compteur"
const val COMPTEUR_REFERENCE_TABLE = "CompteurRef"
const val PHOTO_COMPTEUR_TABLE = "PhotoCompteur"
